#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// include bindings generated by build.rs with bindgen
include!(concat!(env!("OUT_DIR"), "/owl_bindings.rs"));
