#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::unreadable_literal)]
#![allow(clippy::redundant_static_lifetimes)]

// include bindings generated by build.rs with bindgen
include!(concat!(env!("OUT_DIR"), "/aiger_bindings.rs"));
