name: Prepare release
on:
  workflow_dispatch:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  prepare-release-ubuntu:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "10.0"
        directory: ${{ runner.temp }}/llvm

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Set up Java toolchain
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up GraalVM
      run: echo $GRAALVM_11_ROOT/bin >> $GITHUB_PATH

    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: '--release'

    - name: Build dist-tar
      uses: actions-rs/cargo@v1
      with:
        command: dist
        args: 'build-tar'

    - name: Upload dist-tar
      uses: actions/upload-artifact@v2
      with:
        name: dist-tar-linux
        path: target/dist/*.tar.gz
        if-no-files-found: error

    - name: Build dist-deb
      uses: actions-rs/cargo@v1
      with:
        command: dist
        args: 'build-deb'

    - name: Upload dist-deb
      uses: actions/upload-artifact@v2
      with:
        name: dist-deb
        path: target/dist/*.deb
        if-no-files-found: error

    - name: Archive sources
      run: .github/scripts/git-archive-all --format=tar.gz -o strix-src.tar.gz HEAD

    - name: Upload sources
      uses: actions/upload-artifact@v2
      with:
        name: dist-src
        path: strix-src.tar.gz
        if-no-files-found: error

  prepare-release-centos:
    runs-on: ubuntu-20.04
    container:
      image: centos:7
    steps:

    - name: Set up container
      run: |
        yum update -y
        yum install -y git gcc zlib-devel centos-release-scl scl-utils rpm-build
        # need to install this after install scl
        yum install -y llvm-toolset-7
        # update git to use checkout action with submodules
        yum install -y \
          https://repo.ius.io/ius-release-el7.rpm \
          https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        yum swap -y git git224-core

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Set up GraalVM
      uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 21.0.0.2
        native-image: true

    - name: Build dist-rpm
      run: scl enable llvm-toolset-7 'cargo dist build-rpm'

    - name: Upload dist-rpm
      uses: actions/upload-artifact@v2
      with:
        name: dist-rpm
        path: target/dist/*.rpm
        if-no-files-found: error

  prepare-release-archlinux:
    runs-on: ubuntu-20.04
    container:
      image: archlinux:base-devel
    steps:

    - name: Set up container
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm git clang

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Set up GraalVM
      uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 21.0.0.2
        native-image: true

    # fix makepkg to run it as root
    - name: Fix makepkg
      run: sed -e 's/EUID == 0/0/' -i /usr/bin/makepkg

    - name: Build dist-pkg
      run: cargo dist build-pkg

    - name: Upload dist-pkg
      uses: actions/upload-artifact@v2
      with:
        name: dist-pkg
        path: target/dist/*.pkg.tar.zst
        if-no-files-found: error

  prepare-release-macos:
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Set up GraalVM
      uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 21.0.0.2
        native-image: true

    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: '--release'

    - name: Build dist-tar
      uses: actions-rs/cargo@v1
      with:
        command: dist
        args: 'build-tar'

    - name: Upload dist-tar
      uses: actions/upload-artifact@v2
      with:
        name: dist-tar-macos
        path: target/dist/*.tar.gz
        if-no-files-found: error
