name: Prepare release Windows
on:
  workflow_dispatch:

jobs:
  prepare-release-windows:
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "10.0"
        directory: ${{ runner.temp }}/llvm

    - name: Set LIBCLANG_PATH
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $GITHUB_ENV

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Set up GraalVM
      uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 21.1.0
        native-image: true

    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: '--release'

    - name: Cargo run
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: '--release -- --version'

    - name: Build dist-tar
      uses: actions-rs/cargo@v1
      with:
        command: dist
        args: 'build-tar'

    - name: Upload dist-tar
      uses: actions/upload-artifact@v2
      with:
        name: dist-tar-windows
        path: target/dist/*.tar.gz
        if-no-files-found: error
